server:
  port: 8082

spring:
  application:
    name: cover-service

  datasource:
    # (기존 설정 유지)
    url: jdbc:mysql://34.50.47.209:3306/covercloud_cover?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: NewPassword123!

  # 여기를 data.redis로 감싸야 합니다!
  data:
    redis:
      host: 34.50.47.209
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    enabled: false
