server:
  port: 8082

spring:

  application:
    name: cover-service

  datasource:
    url: jdbc:mysql://localhost:3306/covercloud_cover?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: NewPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  jpa:
    hibernate:
      ddl-auto: update

  security:
    enabled: false
