server:
  port: 8083

spring:

  application:
    name: music-service

  datasource:
    url: jdbc:mysql://localhost:3306/covercloud_music?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


  security:
    enabled: false
  
spotify:
  client-id: 2204e48081a84cf495978d562a36eb49
  client-secret: 8d940ca97fa24adcad467f85e169081b